# Generated by Django 5.0 on 2024-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='isarchived',
            field=models.BooleanField(default='false'),
        ),
    ]
