# Generated by Django 5.0 on 2024-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_categorie_isarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
